### ISSUE TITLE
Survivors of the Void Incompatibility's

### ISSUE THREAD

**Issue by VenomGhostVT** [bryantBaumgartner/chaosMode#1]
As of the Survivors of the Void DLC, Chests, void containers, lockboxes, scavenger bags and anything else dropping random loot that requires an interaction (multishop terminals are fine) no longer drop items, the chest animation fails to also play, I have an idea as to what's causing the issue and it might be related to how Chaos Mode can make things like lunar items drop from regular chests, and now with the new void items it doesn't know what to do and just break

Enemies spawned from Chaos Mode also cannot currently spawn as Elites

https://user-images.githubusercontent.com/101408893/157883622-4ad0b9ce-5892-4b33-b922-38839e088eb6.mp4

s

**Comment by bryantBaumgartner** [comment]
Thanks for the feedback @VenomGhostVT. As of the DLC update, some of the dependencies that that mod relied on have changed in a way that prevents things from working properly. I've been messing around with a fix and should be able to update the mod within a few days at most.

**Comment by bryantBaumgartner** [comment]
I pushed a new update that should allow chests to function correctly, as well as include various Corrupted Items. You should be able to install the update in your Mod Manager or download it from here.

I'm still working on the Elite enemy problem, however, so I'll leave the thread open until I get that ironed out.

**Comment by VenomGhostVT** [comment]
Lets go~ that makes me very happy to hear as it is probably genuinely my favourite mod, I absolutely love the Chaos it causes and dragging my friends through, I'll do a run through and report if there's any more new issues 

I don't know where to leave a feature request but would a config option for the purge event be hard to add?

**Comment by VenomGhostVT** [comment]
Bug - It seems that when Chaos activates now it does 10 different events all at once (this could be fun as a config option) 

Most chest items are also spawning as void, not all but the rates might be a lil too high

https://user-images.githubusercontent.com/101408893/158019577-0113a155-4932-45aa-b01f-ee992391d275.mp4

**Comment by bryantBaumgartner** [comment]
Lots of information incoming.

- I went ahead and added new Config settings so you can customize how many items a purge will take (or set it to 0 if you don't want it to trigger) and control the rate at which Void Items spawn. I've also reworked the drop tables for items to make them feel a little bit more natural.

- I did the same for the event system, so you can better decide at what rate events spawn (again, you can set this to 0 if you want).

- I also changed up the way Elites work so they should spawn correctly and appear more often the further you go. This can also be controlled by a Config setting.

- There's also currently a bug that makes Lunar Pod's drop 2 items. I currently have no idea what's causing this, but I like it too much to patch it right now. (Kind of like the bug that made Rusty Lockboxes drop a guaranteed Legendary Item)

- Finally, I wasn't able to replicate the "10-Events-At-Once" bug, but I added a few checks to (hopefully) prevent this from happening again. If this does continue we can take a look at specifics to see if we can narrow down what's happening.

Also, I really appreciate your interest in and enjoyment with the mod. It's very exciting for me to personally hear from people who are having fun using it.

**Comment by VenomGhostVT** [comment]
Yea, the "10 events at once" could just be an incompatibility with a different mod, I didn't have the time to check to narrow it down at the time as I found out about the issue right as I was about to do a multiplayer session, me and my friend still made do though

I'm also very happy to hear about the config settings additions!

Admittedly I went and finally made an account on here finally just to add bug reports for the mod and hope the it was updated so hearing the feedback and additions is great! Great mod from a great mod maker, couldn't ask for more <3

Edit - Can confirm that Elites are spawning correctly and that whatever was causing the "10 events at once" on my end has also been fixed
