### ISSUE TITLE
Mod won't work in multiplayer.

### ISSUE THREAD

**Issue by Graykou** [bryantBaumgartner/chaosMode#3]
When other players enter a mod-enabled room I created, their presence is not shown, they cannot pick a character, and they just disconnect. I'm currently using an alternative to this mod called ChaosMod4Friends. Thanks for making it, hope it gets fixed soon~

**Comment by bryantBaumgartner** [comment]
The most recent patch was meant to address a similar issue to this.

If you're fully up-to-date (v2.2.2), then you can go into your config settings and change 'ArtifactMode' to 'false.' This should allow the mod to work in multiplayer by having it act like earlier versions. (I need to update the README to explain this in more detail).

**Comment by Graykou** [comment]
Sorry for my mistake...I didn't read the config file carefully. Now I can use it in multiplayer.Thanks again.   ：）
