### ISSUE TITLE
Few issues.

### ISSUE THREAD

**Issue by MrPlaner** [bryantBaumgartner/chaosMode#5]
Hey,
Tried to play with Chaos today and noticed few things:
1) Starting items not being distributed to multiplayer participants - instead of 5 everyone got 1.
1.a) Same with singleplayer - only 1 item is being given.
1.b) For some reason another item was given on 2nd stage and then 3rd on next one and so on.
2) Default config or modified config ( events from 60 sec to 90 sec ) stopped in multiplayer after the first event, in single after the 2nd.

Tho few notes:
We do have almost 70 mods in total, from skins to items and new characters: LJwHDHuf3U
There's the code for the mod manager if you wanna see and check yourself.
If you want me to provide anything else let me know, I will try to bug test if need be as well.
Cheers!

**Comment by bryantBaumgartner** [comment]
I haven't updated the mod in a while, and I believe some updates have come out for the game that could be causing problems. I'll try to take a look at what's going on this weekend, but I may need more info to go on.

**Comment by MrPlaner** [comment]
No worries, I know it's been almost 3 months since the last update, and there were few bugfixes and such for RoR in the meantime.
And no rush + again, if you need me to provide logs or anything else let me know!

**Comment by bryantBaumgartner** [comment]
I do have a few questions though that could help me narrow things down.

1. Are you playing with Artifact Mode On or Off?
2. How many players are in these multiplayer lobbies? Is it 4 or less?

**Comment by MrPlaner** [comment]
1) Artifact mode was on, everyone had the same mod manager code mentioned before. Which included the Chaos Mod itself of course.
2) Total of 3 people at the time, aka host + 2 people.

**Comment by bryantBaumgartner** [comment]
I was able to find a bug where the mod thought there was an extra player object, so when it gave out items, either from events or at the beginning of the game, it mistakenly tried to access an inventory that doesn't exist, threw an error and broke. I put in a patch that should fix that bug.

I haven't been able to replicate the mod stopping after a certain number of events, however, when the mod runs into bugs like the one above, it tends to disrupt other processes, so it's very likely that the mysterious extra player caused the timer to stop activating properly.

I'll keep an eye on this thread, but after the next update, Starting Items should be distributed correctly.

**Comment by MrPlaner** [comment]
Alrighty, thank you for your time!
I will check if it works on my and my friends end, possibly today or in upcoming few days and will give info if it works or not.
Cheers!

**Comment by MrPlaner** [comment]
Alright, just checked on solo run - it works just fine.
I get the items, waves spawn every 90 seconds like I set it, nothing seems to get broken.
Again, thank you for your time looking into this, even though the last update was 3 months ago!
